### PR TITLE
Problem: auth isn't tested #20

### PR DESCRIPTION
**Pull request by samuelralak**
Solution: added client side tests for auth pages i.e sign in and sign up. added client side tests for the header

### CODE REVIEW

**Comment by samuelralak** [comment]
@anbud tests are failing yet they are supposed to pass. not sure whats making them fail. could you help me find out? I would also like to know how to fix such cases

**Comment by anbud** [comment]
Sure thing, I'll take a look. :)

**Comment by anbud** [comment]
It should be fixed in #22.

Basically, I've tried debugging it for a while, but it was passing locally all the time, and then I realized that all it was missing are pauses between page loads. When you run tests on localhost, everything happens instantly, so tests pass even without pauses, but in the CI environment, they begin to fail if you don't wait long enough between commands/actions.
As a rule of the thumb, whenever you're loading a new page, wait for about 5-6 seconds for everything to complete. Whenever you click on something or edit something, waiting for 2-3 seconds is a good idea. If you see that tests are failing on the CI, try increasing wait periods, it should help.

*Side note, wdio doesn't work with Node v10.4.1 on Windows, as fibers@2.0.2 don't want to build on Node v10. So, if you want to run tests properly, don't update to Node v10 just yet. I've learned that the hard way and I had to downgrade to Node v9.3.0 in the end. :)*

**Comment by samuelralak** [comment]
aah I see. thats enlightening. I honestly never understood why we needed those pauses until now, I just had them there without quite understanding their relevance. its all crystal clear now.

thanks a lot. grately appreciate this. all noted 👍

**Pull request merged**
