### PR TITLE
Problem: version out of date

### LINKED ISSUE #15: problem: node-sass v3.13.0 in use but too old
problem: node-sass v3.13.0 is too old to work with node 8 and it fails in production.

solution: update to latest version of node-sass. This appears to be a dependency of fourseven:scss@3.13.0

### PR DESCRIPTION
**Pull request by gazhayes**
Solution: update Meteor version. Also update sass version which was causing errors. Resolves #15

### CODE REVIEW

**Comment by gazhayes** [comment]
ping @samuelralak

**Comment by samuelralak** [comment]
@gazhayes just seeing this. apologies

**Comment by gazhayes** [comment]
No worries, with the flood of emails from these repositories I'm surprised you keep up as well as you do!

**Comment by samuelralak** [comment]
haha. I try 😅

**Pull request merged**
