### PR TITLE
problem: user able to start a new application while another exists

### PR DESCRIPTION
**Pull request by AshHimself**
solution: redirect to existing application if one is in progress #35

### CODE REVIEW

**Comment by anbud** [comment]
@AshHimself, do you want to fix the tests, or should I have a look? :)

**Comment by AshHimself** [comment]
I think I asked this to you before, can I be notified when these fail? 

Also, I can take a look at them tonight or you can grab them now i'm fine either way mate.

**Comment by AshHimself** [comment]
Mate I won't get to this tonight, from first looks this may be of a result from @samuelralak new step UI for adding application, albeit I could be wrong.

**Comment by anbud** [comment]
Hey, don't worry about it, I'll merge it and fix it later today. :)

**Comment by anbud** [comment]
It was kinda tricky to spot, but it's fixed in #51. :)

**Pull request merged**
